const carDetails = {
  toyotafortuner: {
    name: 'ToyotaFortuner',
    price: 1800000,
    transmission: 'Otomatis',
    rating: 4.8,
    description: 'Toyota Fortuner adalah SUV premium yang menawarkan kenyamanan dalam perjalanan jauh dan medan sulit, dilengkapi dengan fitur canggih dan keamanan terbaik.',
    image: '/cars/toyotafortuner.jpg',
    plate: 'DD 1234 XY',
    seats: 7,
    purchaseYear: 2022,
    color: 'Black Metallic',
    maxSpeed: '200 km/jam',
    location: 'Makassar',
    fuel: '2.4L Diesel',
  },

  toyotanovaa: {
    name: 'toyotanova',
    price: 1400000,
    transmission: 'Manual',
    rating: 4.7,
    description: 'Toyota Nova adalah MPV yang ideal untuk perjalanan keluarga dengan kabin luas, mesin handal, dan efisiensi bahan bakar yang baik.',
    image: '/cars/toyotanova.jpg',
    plate: 'DD 5678 AB',
    seats: 7,
    purchaseYear: 2021,
    color: 'Silver Metallic',
    maxSpeed: '180 km/jam',
    location: 'Makassar',
    fuel: '1.5L Bensin',
  },

  chevrolet: {
      name: 'Chevrolet',
      price: 1600000,
      transmission: 'Otomatis',
      rating: 4.6,
      description: 'Chevrolet SUV menawarkan keseimbangan sempurna antara performa, kenyamanan, dan desain dengan ruang kabin yang lapang.',
      image: '/cars/Chevrolet.jpg',
      plate: 'DD 9101 CD',
      seats: 7,
      purchaseYear: 2021,
      color: 'Red',
      maxSpeed: '200 km/jam',
      location: 'Makassar',
      fuel: '2.0L Diesel',
    },
    corola: {
      name: 'Corola',
      price: 1300000,
      transmission: 'Otomatis/Manual',
      rating: 4.7,
      description: 'Toyota Corolla menawarkan kenyamanan berkendara dengan desain modern dan efisiensi bahan bakar yang baik.',
      image: '/cars/Corola.jpg',
      plate: 'DD 1122 EF',
      seats: 5,
      purchaseYear: 2020,
      color: 'White',
      maxSpeed: '180 km/jam',
      location: 'Makassar',
      fuel: '1.8L Bensin',
    },

    daihatsu: {
      name: 'Daihatsu',
      price: 1200000,
      transmission: 'Manual',
      rating: 4.5,
      description: 'Daihatsu adalah pilihan kendaraan kompak yang sempurna untuk perjalanan dalam kota dengan efisiensi bahan bakar yang sangat baik.',
      image: '/cars/Daihatsu.jpg',
      plate: 'DD 3456 GH',
      seats: 5,
      purchaseYear: 2020,
      color: 'Blue',
      maxSpeed: '160 km/jam',
      location: 'Makassar',
      fuel: '1.3L Bensin',
    },
    suzuki: {
      name: 'suzuki',
      price: 1250000,
      transmission: 'Otomatis',
      rating: 4.6,
      description: 'Suzuki adalah pilihan kendaraan yang menawarkan keseimbangan antara kenyamanan dan efisiensi bahan bakar untuk perjalanan panjang.',
      image: '/cars/Suzuki.jpg',
      plate: 'DD 6789 IJ',
      seats: 7,
      purchaseYear: 2021,
      color: 'Grey',
      maxSpeed: '175 km/jam',
      location: 'Makassar',
      fuel: '1.6L Bensin',
    },
    toyotanova: {
      name: 'toyotanova',
      price: 1400000,
      transmission: 'Otomatis',
      rating: 4.8,
      description: 'Toyota Nova, MPV dengan ruang kabin luas, sangat cocok untuk keluarga yang mencari kenyamanan dan efisiensi bahan bakar.',
      image: '/cars/Toyotanova.jpg',
      plate: 'DD 4321 KL',
      seats: 7,
      purchaseYear: 2022,
      color: 'Green',
      maxSpeed: '185 km/jam',
      location: 'Makassar',
      fuel: '1.8L Bensin',
    },
    toyotay: {
      name: 'ToyotaY',
      price: 1550000,
      transmission: 'Otomatis',
      rating: 4.9,
      description: 'Toyota Y adalah SUV kompak dengan desain stylish, nyaman digunakan dalam perkotaan dengan fitur keselamatan yang lengkap.',
      image: '/cars/ToyotaY.jpg',
      plate: 'DD 7654 MN',
      seats: 5,
      purchaseYear: 2021,
      color: 'Silver',
      maxSpeed: '190 km/jam',
      location: 'Makassar',
      fuel: '1.5L Bensin',
    },
};

export default carDetails;
